<a href="https://colab.research.google.com/github/mariellemiron/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 6 : Matrix Operations

## Objectives
In this activity, the students will be able to acquire the follow:
1. Familiarize fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

Transposition is a fundamental operation in matrix algebra. The values of a matrix's elements are flipped over its diagonals to transpose it. The rows and columns of the original matrix will be switched as a result of this. As a result, the transpose of a matrix $C$ is denoted by $C^T$. This may now be done programmatically with `np.transpose()` or the `T` function. For instance:

$$A = \begin{bmatrix} 5 & -1 & 2\\0 & -3 &2 \\ 1 & 3 & -9\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 5 & 0 & 1\\-1 & -3 &3 \\ 2& 2 & -9\end{bmatrix}$$

In [ ]:
A = np.array([
    [2 ,5, 0],
    [4, -9, 3],
    [1, 1, 7]
])
A

array([[ 2,  5,  0],
       [ 4, -9,  3],
       [ 1,  1,  7]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 2,  4,  1],
       [ 5, -9,  1],
       [ 0,  3,  7]])

In [ ]:
AT2 = A.T
AT2

array([[ 2,  4,  1],
       [ 5, -9,  1],
       [ 0,  3,  7]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [9,1,-9],
    [5,-8,5],
])
B.shape

(2, 3)

In [ ]:
np.transpose(B).shape

(3, 2)

In [ ]:
B.T.shape

(3, 2)

## Test / Trial

In [ ]:
M=np.array([
    [4,6,4,5],
    [8,9,7,-9]        
])
M.shape

(2, 4)

In [ ]:
np.transpose(M).shape

(4, 2)

In [ ]:
M.T.shape

(4, 2)

In [ ]:
MT = M.T
MT

array([[ 4,  8],
       [ 6,  9],
       [ 4,  7],
       [ 5, -9]])

## Dot Product / Inner Product

If you remember the dot product from the laboratory activity, we'll try to do the same thing with matrices. We'll retrieve the sum of products of the vectors by row-column pairings in matrix dot product. So, if we have two matrices, $X$ and $Y$, we can deduce:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$

Using np.dot(), np.matmul(), or the @ operator.

In [ ]:
Q = np.array([
    [5,4],
    [2,0]
])
W = np.array([
    [-5,-4],
    [-2,2]
])

In [ ]:
np.array_equiv(Q, W)

False

In [ ]:
np.dot(Q,W)

array([[-33, -12],
       [-10,  -8]])

In [ ]:
Q.dot(W)

array([[-33, -12],
       [-10,  -8]])

In [ ]:
Q @ W

array([[-33, -12],
       [-10,  -8]])

In [ ]:
np.matmul(Q,W)

array([[-33, -12],
       [-10,  -8]])

In [ ]:
D = np.array([
    [0,1,2],
    [-3,-4,-5],
    [6,7,8]
])
K = np.array([
    [-9,-10,-11],
    [0,1,2],
    [-3,4,-5]
])

In [ ]:
D @ K

array([[ -6,   9,  -8],
       [ 42,   6,  50],
       [-78, -21, -92]])

In [ ]:
D.dot(K)

array([[ -6,   9,  -8],
       [ 42,   6,  50],
       [-78, -21, -92]])

In [ ]:
np.matmul(D, K)

array([[ -6,   9,  -8],
       [ 42,   6,  50],
       [-78, -21, -92]])

In [ ]:
np.dot(D, K)

array([[ -6,   9,  -8],
       [ 42,   6,  50],
       [-78, -21, -92]])

In comparison to vector dot products, matrix dot products have additional rules. There are fewer limits because vector dot products are only one dimensional. Since we're dealing with Rank 2 vectors, there are a few rules to keep in mind:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Assume you have a matrix A with the shape $(a,b)$, where $a$ and $b$ are any integers. Matrix $B$ should have the shape $(b,c)$, where $b$ and $c$ are any integers, if we want to do a dot product between A and another matrix $B$. As a result, for the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
X = np.array([
    [9, 9,9,4],
    [8, -7,4,7],
    [-5, 6,2,1]
])
Y = np.array([
    [5,-5,7,4],
    [4,-3,1,5],
    [2,0,-1,9]
])
Z = np.array([
    [0,1,1],
    [1,1,2],
    [0,5,9],
    [7,1,2]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 4)
(3, 4)
(4, 3)


In [ ]:
X @ Z

array([[ 37,  67, 116],
       [ 42,  28,  44],
       [ 13,  12,  27]])

In [ ]:
Y @ Z

array([[23, 39, 66],
       [32, 11, 17],
       [63,  6, 11]])

In [ ]:
X @ Y

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
X @ Y.T

array([[ 79,  38,  45],
       [131,  92,  75],
       [-37, -31,  -3]])

In [ ]:
M = np.array([
    [9,-8,7,-6]
])
G = np.array([
    [5,-4,3,-2]
])
print(M.shape)
print(G.shape)

(1, 4)
(1, 4)


In [ ]:
G.T @ M

array([[ 45, -40,  35, -30],
       [-36,  32, -28,  24],
       [ 27, -24,  21, -18],
       [-18,  16, -14,  12]])

In [ ]:
M @ G.T

array([[110]])

### Rule 2: Dot Product has special properties

Dot products are common in matrix algebra, which means they have various distinct qualities that should be taken into account while formulating solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [9,8,7]
])
B = np.array([
    [9,7,8],
    [8,7,9],
    [2,3,5]
])
C = np.array([
    [8,7,8],
    [6,5,4],
    [3,8,7]
])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 8., 7.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
D = A @ (B @ C)
D

array([[ 551,  695,  655],
       [1511, 1877, 1777],
       [2649, 3245, 3085]])

In [ ]:
E = (A @ B) @ C
E

array([[ 551,  695,  655],
       [1511, 1877, 1777],
       [2649, 3245, 3085]])

In [ ]:
np.array_equal(E, M) 

False

In [ ]:
np.array_equiv(D, E)

True

In [ ]:
np.eye(A)

TypeError: ignored

In [ ]:
A @ D

array([[11520, 14184, 13464],
       [25653, 31635, 30015],
       [35590, 43986, 41706]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value that can be calculated using a square matrix. In matrix algebra, the determinant is a fundamental and crucial value. Although it will not be clear how it may be utilized realistically in this laboratory, it will be extensively employed in future lessons. 

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But what about square matrices that aren't in the shape (2,2)? Several strategies, such as co-factor expansion and the minors method, can be used to solve this problem. This can be taught in a laboratory lecture, but we can use Python to perform the difficult computation of high-dimensional matrices programmatically. Using `np.linalg.det()`, we can accomplish this.

In [ ]:
S = np.array([
    [3,2],
    [3,4]
])
np.linalg.det(S)

6.0

In [ ]:
V = np.array([
              [4, 5, 6],
              [9, 3 ,2],
              [1, -2, -1]
])
np.linalg.det(V)

-67.00000000000004

In [ ]:
T = np.array([
    [1,2,3,8],
    [3,4,6,4],
    [1,6,9,2],
    [0,8,3,0]
])
np.linalg.det(T)

827.9999999999999

## Inverse

Another essential operation in matrix algebra is the inverse of a matrix. We can identify a matrix's solvability and characteristic as a system of linear equations by determining its inverse — we'll go over this more in the nect module. The inverse matrix can also be used to solve the problem of divisibility amongst matrices. Although element-by-element division is possible, dividing matrices as a whole is not. Inverse matrices allow a similar process that might be thought of as "splitting" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
C = np.array([
    [8,6],
    [6,-8]
])

np.array(C @ np.linalg.inv(C), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
R = np.array([
              [1, 3, 5],
              [7, 9, 2],
              [-4, 6, 8]
])
T = np.linalg.inv(R)
T

array([[ 0.23255814,  0.02325581, -0.15116279],
       [-0.24806202,  0.10852713,  0.12790698],
       [ 0.30232558, -0.06976744, -0.04651163]])

In [ ]:
R @ T

array([[ 1.00000000e+00,  1.38777878e-17, -3.46944695e-17],
       [ 1.11022302e-16,  1.00000000e+00, -6.93889390e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
M = np.array([
    [1,2,2,3,4,4,5],
    [20,6,6,7,8,8,9],
    [0,1,1,2,3,3,4],
    [10,11,11,10,9,9,11],
    [9,16,8,9,7,7,8],
    [-1,13,13,0,0,1,-1],
    [20,3,0,4,5,15,12],
])
M_inv = np.linalg.inv(M)
np.array(M @ M_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matrix that you have solved is really the inverse, we follow this dot product property for a matrix $M$:

$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.2, 1.0, 0.8],
    [0.5, 0.3, 1.0],
    [0.9, 0.5, 1.9]
])
weights = np.array([
    [0.5, 0.6, 0.7]
])
p_grade = squad @ weights.T
p_grade

array([[1.76],
       [1.13],
       [2.08]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [3]:
D = np.array([
    [8, 4, 24],
    [8, 6, -5],
    [9, 1, 15]          
])

O = np.array([
    [17, 35, 79],
    [6, 51, 5],
    [38, -1, -6]          
])

G = np.array([
    [23, 70, -34],
    [24, -9, 8],
    [34, 2, 46]          
])

Property no.1: $A \cdot B \neq B \cdot A$

In [43]:
W = D @ O
W

array([[1072,  460,  508],
       [ -18,  591,  692],
       [ 729,  351,  626]])

In [42]:
E = O @ D
E

array([[1127,  357, 1418],
       [ 501,  335,  -36],
       [ 242,  140,  827]])

In [44]:
np.array_equiv(W, E)

False

Property no.2: $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [39]:
M = D @ (O @ G)
M

array([[52968, 71916, -9400],
       [37298, -5195, 37172],
       [46475, 49123,  6818]])

In [40]:
Y = (D @ O) @ G
Y 

array([[52968, 71916, -9400],
       [37298, -5195, 37172],
       [46475, 49123,  6818]])

In [41]:
 np.array_equiv(M,Y)

True

Property no.3: $A\cdot(B+C) = A\cdot B + A\cdot C$

In [46]:
I = D @ (O + G)
I

array([[2168, 1032, 1372],
       [ 140, 1087,  238],
       [1470, 1002, 1018]])

In [47]:
S = D @ O + D @ G
S

array([[2168, 1032, 1372],
       [ 140, 1087,  238],
       [1470, 1002, 1018]])

In [48]:
np.array_equiv(I, S)

True

Propery no.4: $(B+C)\cdot A = B\cdot A + C\cdot A$

In [49]:
L = (O + G) @ D
L

array([[1565,  835, 1110],
       [ 693,  385,  705],
       [ 944,  334, 2323]])

In [52]:
U = O @ D + G @ D
U

array([[1565,  835, 1110],
       [ 693,  385,  705],
       [ 944,  334, 2323]])

In [53]:
np.array_equiv(L, U)

True

Property no.5: $A\cdot I = A$

In [18]:
D @ np.eye(3)

array([[ 8.,  4., 24.],
       [ 8.,  6., -5.],
       [ 9.,  1., 15.]])

In [20]:
np.array_equiv(D, D @ np.eye(3))

True

Property no.6:  $A\cdot \emptyset = \emptyset$ 

In [22]:
D @ np.zeros ((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.array_equiv(D@np.zeros((3,3)), np.zeros((3,3)))

True

In [24]:
D.dot(np.zeros(D.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
z_mat = np.zeros (D.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
i_dot_z = D.dot(np.zeros(D.shape))
i_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.array_equal(i_dot_z,z_mat)

True

In [28]:
null_mat = np.empty(D.shape, dtype = float)
null = np.array(null_mat,dtype = float)
print(null)
np.allclose(i_dot_z , null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True